Add ether support in currency class
sparkpointio/sparkswap-sdk pull request #4
Opened 2023-03-12 14:20 UTC by medardm

references #1

2023-03-13 02:53 UTC, swengr-janan approved these changes
Added!

2023-03-13 08:21 UTC, mativanarquero commented on src/entities/currency.ts
> +          case 5:
Replace with Goerli ETH instead of 'ETH' for chainid 5

2023-03-13 09:21 UTC, mativanarquero requested changes

2023-03-13 09:21 UTC, mativanarquero commented on src/entities/currency.ts
> +              return new Currency(18, 'ETH', 'Ethereum')
Replace with Goerli ETH

2023-03-15 03:07 UTC, acirrej approved these changes

2023-03-20 02:34 UTC, swengr-janan approved these changes
AGITH!

2023-03-21 02:50 UTC, merged